## 2021.01.13(Wed)



- 예외처리
  - `except, try, else, remain, finally `

- 영석님 도움

```
첫번째실행(finally는 이미 실행됐으나 출력 X, 오류이기 때문에-> 값 누적) , 두번째실행 에러 없고 실행됐고 내부에 저장되어있던 finally까지 두번 출력인거죠
아마 두번 오류내보시면 이해가 훨씬 잘되실거에요
2번 오류내면 3개의 지조값이 출력돼요 ㅎㅎ
```



- python은 상수가 없다!
- 파일 생성, 읽기
  - `'w', 'r'`

